const { CONFIG } = require("./dist/config/environment.js");
console.log("PK set:", !!CONFIG.PK);
console.log("PROXY:", CONFIG.PROXY_WALLET);
const { ClobClient } = require("@polymarket/clob-client");
const { Wallet } = require("ethers");
const w = new Wallet(CONFIG.PK);
console.log("Signer:", w.address);
const creds = { key: process.env.CLOB_API_KEY || "", secret: process.env.CLOB_SECRET || "", passphrase: process.env.CLOB_PASSPHRASE || "" };
console.log("creds key:", !!creds.key, "secret:", !!creds.secret);
const clob = new ClobClient(CONFIG.CLOB_API_URL, 137, w, creds, 1, CONFIG.PROXY_WALLET);
clob.getBalanceAllowance({ asset_type: "COLLATERAL" }).then(r => console.log("BAL:", JSON.stringify(r))).catch(e => console.error("ERR:", e.message));
